### ISSUE TITLE
relocate Circuit Maintenance menu items under Circuit menu 

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-circuit-maintenance#248] opened 2023-03-24 00:35 UTC
### Proposed Functionality 

Not sure this was ever discussed, but it just seems logical to navigate to Circuits -> Circuit Notifications vs. Plugins -> Circuit Notifications.  Assuming URL doesn't change, why not?

**Comment by jvanderaa** [comment] 2023-03-28 13:08
Will get this in and release a 1.0.0 for this

**Comment by glennmatthews** [comment] 2023-12-07 16:11
duplicate of #202?

**Comment by chadell** [comment] 2023-12-11 06:31
This is done

**Closed by chadell** 2023-12-11 06:31 UTC
